// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH4YBSXtrsJ5GjrA6qjYNit0RYujhYdR0',
    appId: '1:235674102487:web:3e07a1a7c126bb82ebde92',
    messagingSenderId: '235674102487',
    projectId: 'coinease-b2805',
    authDomain: 'coinease-b2805.firebaseapp.com',
    storageBucket: 'coinease-b2805.appspot.com',
    measurementId: 'G-W1LW4C40DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5iG8rzhjOOUnMKmhqjU7gn7Fg3zr0CqA',
    appId: '1:235674102487:android:724a403fb097485debde92',
    messagingSenderId: '235674102487',
    projectId: 'coinease-b2805',
    storageBucket: 'coinease-b2805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEQJ3zSBW4sSM_Byw-NoGB8PiD2vc5mSs',
    appId: '1:235674102487:ios:0c4e9ba02aaec265ebde92',
    messagingSenderId: '235674102487',
    projectId: 'coinease-b2805',
    storageBucket: 'coinease-b2805.appspot.com',
    iosBundleId: 'com.example.coinEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEQJ3zSBW4sSM_Byw-NoGB8PiD2vc5mSs',
    appId: '1:235674102487:ios:f348ca68a03c5ed8ebde92',
    messagingSenderId: '235674102487',
    projectId: 'coinease-b2805',
    storageBucket: 'coinease-b2805.appspot.com',
    iosBundleId: 'com.example.coinEase.RunnerTests',
  );
}
